### PR TITLE
 convert uniqueIdOfCurrentPattern to string  and fix bug of simple pattern return more than 9 digits

### PR DESCRIPTION
**Pull request by dimohamdy**
fix this bug
https://github.com/freesuraj/SPPatternLock/issues/8

### CODE REVIEW

**Comment by freesuraj** [comment]
Hi Ahmed,

Thanks for touching the issue. 

However, it appears that the solution does not produce a unique ID for a given pattern. Case in point: say for a 4x4 pattern. I touch points 1, 0 and 4 the uniqueID (String) generated is 104. I get the same uniqueID when I touch points 10 and 4. 

If you could review this, I would be glad to merge your pull request.

Thank you,
Suraj

**Comment by dimohamdy** [comment]
ok i can add any separator character between each number like "1,0,4" and other "10,4"
i try to convert it because i don't know 
 how i can get the sequence of touched nodes from your unique ID ?

**Comment by freesuraj** [comment]
That's a good question Ahmed.
When it was designed, the pattern is translated into an unique code. Technically it won't be possible to know the exact sequence of the numbers you selected. The way it would work is like encrypted password. Instead of decrypting the password and checking if it is equal to the input value, you encrypt the input and see if it matches with the existing value. I would think this should suffice for a pattern lock style password protection.

Is there any particular reason you need to get the sequence of the numbers used in the pattern? If it does indeed make sense, I guess you can define a parameter ( or a function) to get back the sequences of the input.

**Comment by dimohamdy** [comment]
i will make this

**Comment by dimohamdy** [comment]
@freesuraj  can you check now

**Comment by freesuraj** [comment]
This looks good. Looks like the LockScreen already had a parameter to hold the cells in order.

**Pull request merged**
